name: Populator
on: push
jobs:
  Populate: 
    runs-on: [ubuntu-latest]
    name: Populate
    steps:
     - name: Check out Code
       uses: actions/checkout@v2
       
     - name: Run Populator
       run: |
         echo "populating yml"
