name: 'Release'
on: 
  workflow_dispatch:
    inputs: 
      version:
        type: choice
        options:
            - major
            - minor
jobs:
  release:
    runs-on: [ubuntu-latest]
    name: 'Release'
    steps:
      - name: Checkout
        uses: action/checkout@v2
